/**
 * Autogenerated by scripts/sync-contracts.mjs.
 * Do not edit manually.
 */

export { identityRegistryAbi } from './identityRegistry';
export { trustScoreAbi } from './trustScore';
export { verificationManagerAbi } from './verificationManager';
export { verificationLoggerAbi } from './verificationLogger';
export { organizationManagerAbi } from './organizationManager';
export { zkProofManagerAbi } from './zkProofManager';
