/**
 * Autogenerated by scripts/sync-contracts.mjs.
 * Do not edit manually.
 */

export const verificationManagerAbi = [
    {
        "type": "constructor",
        "inputs": [
            {
                "name": "admin",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "identityRegistry_",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "trustScore_",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "DEFAULT_ADMIN_ROLE",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "IDENTITY_REGISTRY",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "contract IIdentityRegistry"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "getProvider",
        "inputs": [
            {
                "name": "provider",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "tuple",
                "internalType": "struct VerificationTypes.Provider",
                "components": [
                    {
                        "name": "name",
                        "type": "string",
                        "internalType": "string"
                    },
                    {
                        "name": "metadataURI",
                        "type": "string",
                        "internalType": "string"
                    },
                    {
                        "name": "active",
                        "type": "bool",
                        "internalType": "bool"
                    },
                    {
                        "name": "addedAt",
                        "type": "uint64",
                        "internalType": "uint64"
                    }
                ]
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "getRoleAdmin",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "getVerification",
        "inputs": [
            {
                "name": "verificationId",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "tuple",
                "internalType": "struct VerificationTypes.VerificationRecord",
                "components": [
                    {
                        "name": "id",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "identityId",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "templateId",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "provider",
                        "type": "address",
                        "internalType": "address"
                    },
                    {
                        "name": "status",
                        "type": "uint8",
                        "internalType": "enum VerificationTypes.VerificationStatus"
                    },
                    {
                        "name": "evidenceURI",
                        "type": "string",
                        "internalType": "string"
                    },
                    {
                        "name": "issuedAt",
                        "type": "uint64",
                        "internalType": "uint64"
                    },
                    {
                        "name": "expiresAt",
                        "type": "uint64",
                        "internalType": "uint64"
                    }
                ]
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "grantRole",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "hasRole",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "recordAadhaarVerification",
        "inputs": [
            {
                "name": "identityId",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "evidenceURI",
                "type": "string",
                "internalType": "string"
            },
            {
                "name": "expiresAt",
                "type": "uint64",
                "internalType": "uint64"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "recordFaceVerification",
        "inputs": [
            {
                "name": "identityId",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "evidenceURI",
                "type": "string",
                "internalType": "string"
            },
            {
                "name": "expiresAt",
                "type": "uint64",
                "internalType": "uint64"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "recordIncomeVerification",
        "inputs": [
            {
                "name": "identityId",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "evidenceURI",
                "type": "string",
                "internalType": "string"
            },
            {
                "name": "expiresAt",
                "type": "uint64",
                "internalType": "uint64"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "recordVerification",
        "inputs": [
            {
                "name": "identityId",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "templateId",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "evidenceURI",
                "type": "string",
                "internalType": "string"
            },
            {
                "name": "expiresAt",
                "type": "uint64",
                "internalType": "uint64"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "registerProvider",
        "inputs": [
            {
                "name": "provider",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "name",
                "type": "string",
                "internalType": "string"
            },
            {
                "name": "metadataURI",
                "type": "string",
                "internalType": "string"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "renounceRole",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "callerConfirmation",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "revokeRole",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "setProviderStatus",
        "inputs": [
            {
                "name": "provider",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "active",
                "type": "bool",
                "internalType": "bool"
            },
            {
                "name": "metadataURI",
                "type": "string",
                "internalType": "string"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "setTrustScore",
        "inputs": [
            {
                "name": "newTrustScore",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "setVerificationStatus",
        "inputs": [
            {
                "name": "verificationId",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "status",
                "type": "uint8",
                "internalType": "enum VerificationTypes.VerificationStatus"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "supportsInterface",
        "inputs": [
            {
                "name": "interfaceId",
                "type": "bytes4",
                "internalType": "bytes4"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "trustScore",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "contract ITrustScore"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "event",
        "name": "ProviderRegistered",
        "inputs": [
            {
                "name": "provider",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "name",
                "type": "string",
                "indexed": false,
                "internalType": "string"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "ProviderStatusChanged",
        "inputs": [
            {
                "name": "provider",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "active",
                "type": "bool",
                "indexed": false,
                "internalType": "bool"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "RoleAdminChanged",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "previousAdminRole",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "newAdminRole",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "RoleGranted",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "account",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "sender",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "RoleRevoked",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "account",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "sender",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "VerificationRecorded",
        "inputs": [
            {
                "name": "verificationId",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "identityId",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "templateId",
                "type": "bytes32",
                "indexed": false,
                "internalType": "bytes32"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "VerificationStatusChanged",
        "inputs": [
            {
                "name": "verificationId",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "status",
                "type": "uint8",
                "indexed": false,
                "internalType": "enum VerificationTypes.VerificationStatus"
            }
        ],
        "anonymous": false
    },
    {
        "type": "error",
        "name": "AccessControlBadConfirmation",
        "inputs": []
    },
    {
        "type": "error",
        "name": "AccessControlUnauthorizedAccount",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "neededRole",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ]
    },
    {
        "type": "error",
        "name": "IdentityInactive",
        "inputs": []
    },
    {
        "type": "error",
        "name": "InvalidInput",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotAuthorized",
        "inputs": []
    },
    {
        "type": "error",
        "name": "VerificationProviderNotFound",
        "inputs": []
    },
    {
        "type": "error",
        "name": "VerificationRecordNotFound",
        "inputs": []
    }
] as const;
