/**
 * Autogenerated by scripts/sync-contracts.mjs.
 * Do not edit manually.
 */

export const zkProofManagerAbi = [
    {
        "type": "constructor",
        "inputs": [
            {
                "name": "admin",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "initialTypes",
                "type": "tuple[]",
                "internalType": "struct ZKProofManager.ProofTypeConfig[]",
                "components": [
                    {
                        "name": "name",
                        "type": "string",
                        "internalType": "string"
                    },
                    {
                        "name": "verifier",
                        "type": "address",
                        "internalType": "address"
                    },
                    {
                        "name": "active",
                        "type": "bool",
                        "internalType": "bool"
                    }
                ]
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "DEFAULT_ADMIN_ROLE",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "PROOF_ADMIN_ROLE",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "ROOT_MANAGER_ROLE",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "addProofType",
        "inputs": [
            {
                "name": "name",
                "type": "string",
                "internalType": "string"
            },
            {
                "name": "verifier",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "active",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "anchorRoot",
        "inputs": [
            {
                "name": "root",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "getAllProofTypes",
        "inputs": [],
        "outputs": [
            {
                "name": "list",
                "type": "tuple[]",
                "internalType": "struct IZKProofManager.ProofTypeInfo[]",
                "components": [
                    {
                        "name": "name",
                        "type": "string",
                        "internalType": "string"
                    },
                    {
                        "name": "verifier",
                        "type": "address",
                        "internalType": "address"
                    },
                    {
                        "name": "active",
                        "type": "bool",
                        "internalType": "bool"
                    }
                ]
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "getProofType",
        "inputs": [
            {
                "name": "typeId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "tuple",
                "internalType": "struct IZKProofManager.ProofTypeInfo",
                "components": [
                    {
                        "name": "name",
                        "type": "string",
                        "internalType": "string"
                    },
                    {
                        "name": "verifier",
                        "type": "address",
                        "internalType": "address"
                    },
                    {
                        "name": "active",
                        "type": "bool",
                        "internalType": "bool"
                    }
                ]
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "getRoleAdmin",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "grantRole",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "hasRole",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "isValidRoot",
        "inputs": [
            {
                "name": "root",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "proofTypeCount",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "renounceRole",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "callerConfirmation",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "resolveTypeId",
        "inputs": [
            {
                "name": "name",
                "type": "string",
                "internalType": "string"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "revokeRole",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "revokeRoot",
        "inputs": [
            {
                "name": "root",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "rootTimestamps",
        "inputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "supportsInterface",
        "inputs": [
            {
                "name": "interfaceId",
                "type": "bytes4",
                "internalType": "bytes4"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "updateProofType",
        "inputs": [
            {
                "name": "typeId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "verifier",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "active",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "usedNullifier",
        "inputs": [
            {
                "name": "nullifier",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "verifyAgeMaxProof",
        "inputs": [
            {
                "name": "root",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "nullifier",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "proof",
                "type": "tuple",
                "internalType": "struct IZKProofManager.Proof",
                "components": [
                    {
                        "name": "a",
                        "type": "uint256[2]",
                        "internalType": "uint256[2]"
                    },
                    {
                        "name": "b",
                        "type": "uint256[2][2]",
                        "internalType": "uint256[2][2]"
                    },
                    {
                        "name": "c",
                        "type": "uint256[2]",
                        "internalType": "uint256[2]"
                    }
                ]
            },
            {
                "name": "publicSignals",
                "type": "uint256[]",
                "internalType": "uint256[]"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "verifyAgeProof",
        "inputs": [
            {
                "name": "root",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "nullifier",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "proof",
                "type": "tuple",
                "internalType": "struct IZKProofManager.Proof",
                "components": [
                    {
                        "name": "a",
                        "type": "uint256[2]",
                        "internalType": "uint256[2]"
                    },
                    {
                        "name": "b",
                        "type": "uint256[2][2]",
                        "internalType": "uint256[2][2]"
                    },
                    {
                        "name": "c",
                        "type": "uint256[2]",
                        "internalType": "uint256[2]"
                    }
                ]
            },
            {
                "name": "publicSignals",
                "type": "uint256[]",
                "internalType": "uint256[]"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "verifyAttrProof",
        "inputs": [
            {
                "name": "root",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "nullifier",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "proof",
                "type": "tuple",
                "internalType": "struct IZKProofManager.Proof",
                "components": [
                    {
                        "name": "a",
                        "type": "uint256[2]",
                        "internalType": "uint256[2]"
                    },
                    {
                        "name": "b",
                        "type": "uint256[2][2]",
                        "internalType": "uint256[2][2]"
                    },
                    {
                        "name": "c",
                        "type": "uint256[2]",
                        "internalType": "uint256[2]"
                    }
                ]
            },
            {
                "name": "publicSignals",
                "type": "uint256[]",
                "internalType": "uint256[]"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "verifyIncomeProof",
        "inputs": [
            {
                "name": "root",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "nullifier",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "proof",
                "type": "tuple",
                "internalType": "struct IZKProofManager.Proof",
                "components": [
                    {
                        "name": "a",
                        "type": "uint256[2]",
                        "internalType": "uint256[2]"
                    },
                    {
                        "name": "b",
                        "type": "uint256[2][2]",
                        "internalType": "uint256[2][2]"
                    },
                    {
                        "name": "c",
                        "type": "uint256[2]",
                        "internalType": "uint256[2]"
                    }
                ]
            },
            {
                "name": "publicSignals",
                "type": "uint256[]",
                "internalType": "uint256[]"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "verifyProof",
        "inputs": [
            {
                "name": "typeId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "root",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "nullifier",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "proof",
                "type": "tuple",
                "internalType": "struct IZKProofManager.Proof",
                "components": [
                    {
                        "name": "a",
                        "type": "uint256[2]",
                        "internalType": "uint256[2]"
                    },
                    {
                        "name": "b",
                        "type": "uint256[2][2]",
                        "internalType": "uint256[2][2]"
                    },
                    {
                        "name": "c",
                        "type": "uint256[2]",
                        "internalType": "uint256[2]"
                    }
                ]
            },
            {
                "name": "publicSignals",
                "type": "uint256[]",
                "internalType": "uint256[]"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "event",
        "name": "ProofTypeAdded",
        "inputs": [
            {
                "name": "typeId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "name",
                "type": "string",
                "indexed": false,
                "internalType": "string"
            },
            {
                "name": "verifier",
                "type": "address",
                "indexed": false,
                "internalType": "address"
            },
            {
                "name": "active",
                "type": "bool",
                "indexed": false,
                "internalType": "bool"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "ProofTypeUpdated",
        "inputs": [
            {
                "name": "typeId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "verifier",
                "type": "address",
                "indexed": false,
                "internalType": "address"
            },
            {
                "name": "active",
                "type": "bool",
                "indexed": false,
                "internalType": "bool"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "ProofVerified",
        "inputs": [
            {
                "name": "caller",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "typeId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "root",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "nullifier",
                "type": "bytes32",
                "indexed": false,
                "internalType": "bytes32"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "RoleAdminChanged",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "previousAdminRole",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "newAdminRole",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "RoleGranted",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "account",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "sender",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "RoleRevoked",
        "inputs": [
            {
                "name": "role",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "account",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "sender",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "RootAnchored",
        "inputs": [
            {
                "name": "root",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "timestamp",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "RootRevoked",
        "inputs": [
            {
                "name": "root",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            }
        ],
        "anonymous": false
    },
    {
        "type": "error",
        "name": "AccessControlBadConfirmation",
        "inputs": []
    },
    {
        "type": "error",
        "name": "AccessControlUnauthorizedAccount",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "neededRole",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ]
    },
    {
        "type": "error",
        "name": "InvalidAddress",
        "inputs": []
    },
    {
        "type": "error",
        "name": "InvalidName",
        "inputs": []
    },
    {
        "type": "error",
        "name": "InvalidSignals",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NullifierAlreadyUsed",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ProofTypeInactive",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ProofTypeNameTaken",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ProofTypeNotFound",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ProofVerificationFailed",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ReentrancyGuardReentrantCall",
        "inputs": []
    },
    {
        "type": "error",
        "name": "RootNotAnchored",
        "inputs": []
    }
] as const;
